/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package document.search.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Body information of the event */
@org.apache.avro.specific.AvroGenerated
public class DocumentEventEventBody extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4357976381479284632L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentEventEventBody\",\"namespace\":\"document.search.avro.model\",\"doc\":\"Body information of the event\",\"fields\":[{\"name\":\"documentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"UUID of the transaction\"},{\"name\":\"tenentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Tenant ID that initiated the transaction\"},{\"name\":\"transactionType\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionType\",\"symbols\":[\"INDEX\",\"DELETE\"]},\"doc\":\"Transaction type. Future values might be added\"},{\"name\":\"date\",\"type\":\"long\",\"doc\":\"The timestamp when the transaction event was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentEventEventBody> ENCODER =
      new BinaryMessageEncoder<DocumentEventEventBody>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentEventEventBody> DECODER =
      new BinaryMessageDecoder<DocumentEventEventBody>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentEventEventBody> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentEventEventBody> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentEventEventBody> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentEventEventBody>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentEventEventBody to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentEventEventBody from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentEventEventBody instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentEventEventBody fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** UUID of the transaction */
  private java.lang.String documentId;
  /** Tenant ID that initiated the transaction */
  private java.lang.String tenentId;
  /** Transaction type. Future values might be added */
  private document.search.avro.model.TransactionType transactionType;
  /** The timestamp when the transaction event was generated */
  private long date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentEventEventBody() {}

  /**
   * All-args constructor.
   * @param documentId UUID of the transaction
   * @param tenentId Tenant ID that initiated the transaction
   * @param transactionType Transaction type. Future values might be added
   * @param date The timestamp when the transaction event was generated
   */
  public DocumentEventEventBody(java.lang.String documentId, java.lang.String tenentId, document.search.avro.model.TransactionType transactionType, java.lang.Long date) {
    this.documentId = documentId;
    this.tenentId = tenentId;
    this.transactionType = transactionType;
    this.date = date;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return documentId;
    case 1: return tenentId;
    case 2: return transactionType;
    case 3: return date;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: documentId = value$ != null ? value$.toString() : null; break;
    case 1: tenentId = value$ != null ? value$.toString() : null; break;
    case 2: transactionType = (document.search.avro.model.TransactionType)value$; break;
    case 3: date = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'documentId' field.
   * @return UUID of the transaction
   */
  public java.lang.String getDocumentId() {
    return documentId;
  }


  /**
   * Sets the value of the 'documentId' field.
   * UUID of the transaction
   * @param value the value to set.
   */
  public void setDocumentId(java.lang.String value) {
    this.documentId = value;
  }

  /**
   * Gets the value of the 'tenentId' field.
   * @return Tenant ID that initiated the transaction
   */
  public java.lang.String getTenentId() {
    return tenentId;
  }


  /**
   * Sets the value of the 'tenentId' field.
   * Tenant ID that initiated the transaction
   * @param value the value to set.
   */
  public void setTenentId(java.lang.String value) {
    this.tenentId = value;
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return Transaction type. Future values might be added
   */
  public document.search.avro.model.TransactionType getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * Transaction type. Future values might be added
   * @param value the value to set.
   */
  public void setTransactionType(document.search.avro.model.TransactionType value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The timestamp when the transaction event was generated
   */
  public long getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * The timestamp when the transaction event was generated
   * @param value the value to set.
   */
  public void setDate(long value) {
    this.date = value;
  }

  /**
   * Creates a new DocumentEventEventBody RecordBuilder.
   * @return A new DocumentEventEventBody RecordBuilder
   */
  public static document.search.avro.model.DocumentEventEventBody.Builder newBuilder() {
    return new document.search.avro.model.DocumentEventEventBody.Builder();
  }

  /**
   * Creates a new DocumentEventEventBody RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentEventEventBody RecordBuilder
   */
  public static document.search.avro.model.DocumentEventEventBody.Builder newBuilder(document.search.avro.model.DocumentEventEventBody.Builder other) {
    if (other == null) {
      return new document.search.avro.model.DocumentEventEventBody.Builder();
    } else {
      return new document.search.avro.model.DocumentEventEventBody.Builder(other);
    }
  }

  /**
   * Creates a new DocumentEventEventBody RecordBuilder by copying an existing DocumentEventEventBody instance.
   * @param other The existing instance to copy.
   * @return A new DocumentEventEventBody RecordBuilder
   */
  public static document.search.avro.model.DocumentEventEventBody.Builder newBuilder(document.search.avro.model.DocumentEventEventBody other) {
    if (other == null) {
      return new document.search.avro.model.DocumentEventEventBody.Builder();
    } else {
      return new document.search.avro.model.DocumentEventEventBody.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentEventEventBody instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentEventEventBody>
    implements org.apache.avro.data.RecordBuilder<DocumentEventEventBody> {

    /** UUID of the transaction */
    private java.lang.String documentId;
    /** Tenant ID that initiated the transaction */
    private java.lang.String tenentId;
    /** Transaction type. Future values might be added */
    private document.search.avro.model.TransactionType transactionType;
    /** The timestamp when the transaction event was generated */
    private long date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(document.search.avro.model.DocumentEventEventBody.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.tenentId)) {
        this.tenentId = data().deepCopy(fields()[1].schema(), other.tenentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[2].schema(), other.transactionType);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentEventEventBody instance
     * @param other The existing instance to copy.
     */
    private Builder(document.search.avro.model.DocumentEventEventBody other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.documentId)) {
        this.documentId = data().deepCopy(fields()[0].schema(), other.documentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.tenentId)) {
        this.tenentId = data().deepCopy(fields()[1].schema(), other.tenentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[2].schema(), other.transactionType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'documentId' field.
      * UUID of the transaction
      * @return The value.
      */
    public java.lang.String getDocumentId() {
      return documentId;
    }


    /**
      * Sets the value of the 'documentId' field.
      * UUID of the transaction
      * @param value The value of 'documentId'.
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder setDocumentId(java.lang.String value) {
      validate(fields()[0], value);
      this.documentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'documentId' field has been set.
      * UUID of the transaction
      * @return True if the 'documentId' field has been set, false otherwise.
      */
    public boolean hasDocumentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'documentId' field.
      * UUID of the transaction
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder clearDocumentId() {
      documentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'tenentId' field.
      * Tenant ID that initiated the transaction
      * @return The value.
      */
    public java.lang.String getTenentId() {
      return tenentId;
    }


    /**
      * Sets the value of the 'tenentId' field.
      * Tenant ID that initiated the transaction
      * @param value The value of 'tenentId'.
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder setTenentId(java.lang.String value) {
      validate(fields()[1], value);
      this.tenentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'tenentId' field has been set.
      * Tenant ID that initiated the transaction
      * @return True if the 'tenentId' field has been set, false otherwise.
      */
    public boolean hasTenentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'tenentId' field.
      * Tenant ID that initiated the transaction
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder clearTenentId() {
      tenentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionType' field.
      * Transaction type. Future values might be added
      * @return The value.
      */
    public document.search.avro.model.TransactionType getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * Transaction type. Future values might be added
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder setTransactionType(document.search.avro.model.TransactionType value) {
      validate(fields()[2], value);
      this.transactionType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * Transaction type. Future values might be added
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * Transaction type. Future values might be added
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * The timestamp when the transaction event was generated
      * @return The value.
      */
    public long getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * The timestamp when the transaction event was generated
      * @param value The value of 'date'.
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder setDate(long value) {
      validate(fields()[3], value);
      this.date = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * The timestamp when the transaction event was generated
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'date' field.
      * The timestamp when the transaction event was generated
      * @return This builder.
      */
    public document.search.avro.model.DocumentEventEventBody.Builder clearDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentEventEventBody build() {
      try {
        DocumentEventEventBody record = new DocumentEventEventBody();
        record.documentId = fieldSetFlags()[0] ? this.documentId : (java.lang.String) defaultValue(fields()[0]);
        record.tenentId = fieldSetFlags()[1] ? this.tenentId : (java.lang.String) defaultValue(fields()[1]);
        record.transactionType = fieldSetFlags()[2] ? this.transactionType : (document.search.avro.model.TransactionType) defaultValue(fields()[2]);
        record.date = fieldSetFlags()[3] ? this.date : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentEventEventBody>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentEventEventBody>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentEventEventBody>
    READER$ = (org.apache.avro.io.DatumReader<DocumentEventEventBody>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.documentId);

    out.writeString(this.tenentId);

    out.writeEnum(this.transactionType.ordinal());

    out.writeLong(this.date);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.documentId = in.readString();

      this.tenentId = in.readString();

      this.transactionType = document.search.avro.model.TransactionType.values()[in.readEnum()];

      this.date = in.readLong();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.documentId = in.readString();
          break;

        case 1:
          this.tenentId = in.readString();
          break;

        case 2:
          this.transactionType = document.search.avro.model.TransactionType.values()[in.readEnum()];
          break;

        case 3:
          this.date = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










