/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package document.search.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TransactionType implements org.apache.avro.generic.GenericEnumSymbol<TransactionType> {
  INDEX, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionType\",\"namespace\":\"document.search.avro.model\",\"symbols\":[\"INDEX\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
